const $=id=>document.getElementById(id);
const client=window.supabase.createClient(window.TOPDECK_SUPABASE_URL,window.TOPDECK_SUPABASE_ANON_KEY);
let releases=[],artists={};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const safe=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:""}catch{return""}};
const date=v=>v?new Date(v).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"}):"Not set";
function msg(t,type=""){const e=$("adminStatus");e.textContent=t;e.className=`notice ${type}`.trim()}
function loginMsg(t,type=""){const e=$("loginStatus");e.textContent=t;e.className=`notice ${type}`.trim()}
$("togglePassword").onclick=()=>{const i=$("password"),b=$("togglePassword"),show=i.type==="text";i.type=show?"password":"text";b.textContent=show?"Show password":"Hide password"};
$("loginBtn").onclick=async()=>{loginMsg("Signing in...");const{error}=await client.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)return loginMsg(error.message,"error");verifyAdmin()};
$("signOutBtn").onclick=async()=>{await client.auth.signOut();location.reload()};
$("refreshBtn").onclick=load;$("searchInput").oninput=render;$("statusFilter").onchange=render;
async function verifyAdmin(){const{data:{user}}=await client.auth.getUser();if(!user)return;const{data,error}=await client.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(error||!data){await client.auth.signOut();return loginMsg("This account does not have admin access.","error")} $("loginCard").classList.add("hidden");$("dashboard").classList.remove("hidden");$("signOutBtn").classList.remove("hidden");load()}
async function load(){msg("Loading dashboard...");const[p,r]=await Promise.all([client.from("artist_profiles").select("*"),client.from("release_submissions").select("*").order("created_at",{ascending:false})]);if(r.error)return msg(r.error.message,"error");artists=Object.fromEntries((p.data||[]).map(x=>[x.user_id,x]));releases=r.data||[];
$("artistCount").textContent=new Set(releases.map(x=>x.user_id)).size||Object.keys(artists).length;$("releaseCount").textContent=releases.length;$("pendingCount").textContent=releases.filter(x=>x.status==="Pending").length;$("approvedCount").textContent=releases.filter(x=>x.status==="Approved").length;$("changesCount").textContent=releases.filter(x=>x.status==="Needs Changes").length;$("rejectedCount").textContent=releases.filter(x=>x.status==="Rejected").length;render();msg("Dashboard loaded.","success")}
function render(){const q=$("searchInput").value.toLowerCase(),s=$("statusFilter").value;const list=releases.filter(r=>{const a=artists[r.user_id]?.artist_name||r.user_id;return(!q||[a,r.title,r.featured_artists,r.admin_notes,r.notes].join(" ").toLowerCase().includes(q))&&(s==="All"||r.status===s)});
$("releaseList").innerHTML=list.length?list.map(r=>{const p=artists[r.user_id]||{},c=safe(r.cover_url),a=safe(r.audio_url);return `<article class="release"><div>${c?`<a href="${c}" target="_blank"><img class="cover" src="${c}" alt=""></a>`:`<div class="cover placeholder">No cover</div>`}</div><div><div class="artist">${esc(p.artist_name||r.user_id)}</div><h3>${esc(r.title)}</h3><div class="small">${esc(r.release_type||"Release")}${r.featured_artists?` • Featuring ${esc(r.featured_artists)}`:""}</div><div class="small">Release: ${esc(date(r.release_date))}</div><div class="small">Submitted: ${esc(date(r.created_at))}</div></div><div class="review"><div class="small"><strong>Artist notes</strong></div><div class="small">${esc(r.notes||"No artist notes.")}</div>${a?`<audio controls preload="none" src="${a}"></audio><div class="small"><a href="${a}" target="_blank">Open audio file</a></div>`:`<div class="small" style="margin-top:10px">No audio uploaded.</div>`}</div><div class="actions"><select id="status-${r.id}">${["Pending","Approved","Needs Changes","Rejected"].map(x=>`<option ${r.status===x?"selected":""}>${x}</option>`).join("")}</select><textarea id="note-${r.id}" placeholder="Admin note">${esc(r.admin_notes||"")}</textarea><button class="primary" onclick="saveRelease('${r.id}')">Save Update</button></div></article>`}).join(""):`<div class="small" style="text-align:center;padding:30px">No releases match this view.</div>`}
window.saveRelease=async id=>{const{data:{user}}=await client.auth.getUser(),status=$(`status-${id}`).value,payload={status,admin_notes:$(`note-${id}`).value.trim(),updated_at:new Date().toISOString(),reviewed_at:new Date().toISOString(),reviewed_by:user.id,workflow_stage:status};if(status==="Approved")payload.approved_at=new Date().toISOString();msg("Saving update...");const{error}=await client.from("release_submissions").update(payload).eq("id",id);if(error)return msg(error.message,"error");await load();msg("Release updated successfully.","success")};
client.auth.onAuthStateChange(()=>verifyAdmin());verifyAdmin();